# Docker Compose for Organized Agents Development
version: '3.8'

services:
  organized-agents-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - organized-agents-claude-config:/root/.claude
      - organized-agents-cargo-cache:/root/.cargo
      - organized-agents-bun-cache:/root/.bun
    ports:
      - "1420:1420"  # Vite dev server
      - "1421:1421"  # Vite HMR websocket
      - "3000:3000"  # Alternative port
      - "8080:8080"  # Future API server
    environment:
      - AUTH_MODE=claude-max
      - DEBUG_MODE=true
      - RUST_LOG=debug
      - TAURI_DEV_HOST=0.0.0.0
    command: bash
    stdin_open: true
    tty: true
    networks:
      - organized-agents-network

  # Future: Routing server service
  # routing-api:
  #   build:
  #     context: ../routing-server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - organized-agents-dev
  #   networks:
  #     - organized-agents-network

volumes:
  organized-agents-claude-config:
    driver: local
  organized-agents-cargo-cache:
    driver: local
  organized-agents-bun-cache:
    driver: local

networks:
  organized-agents-network:
    driver: bridge